name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test Code
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt black

      - name: Run Lint
        run: black --check .
        continue-on-error: true

      - name: Run Tests
        run: |
          python manage.py migrate
          python manage.py test

  build:
    name: Build Docker Image
    environment: staging
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build Docker Image
        run: |
          docker build -t test_image .
